en/px-common.json, en/px-platform.json, es/px-common.json, es/px-platform.json
Additions in pxPlatform and pxCommon namespaces.
=> pxPlatform + pxCommon additions

en/px-platform.json
New copies mostly for the landing page
=> Landing mostly

en/px-common.json, es/px-common.json
=> New copies

de/px-common.json, de/px-emails.json, de/px-platform.json
German copies for:
- WUD EOL
- Emails
=> Adds german copies for WUD EOL

de/px-emails.json, en-GB/px-emails.json, en/px-emails.json, es/px-emails.json
Adds copies that payment-service cron job will use when creating paypal payouts.
=> Adds copies for payment-service cron job

en/px-emails.json, en/px-platform.json
Adds copies for the PaypalIntegration
=> Adds Paypal integration copies

en/px-emails.json, en/px-platform.json, es/px-emails.json, es/px-platform.json
=> More PayPal copies

de/px-emails.json, de/px-platform.json
Add German copies for Paypal Integration
=> Add German copies for Paypal Integration

de/px-emails.json, de/px-platform.json, en-GB/px-emails.json, en/px-emails.json, es/px-emails.json
German copies fix and revoke email template spacings
=> German copies fix and revoke email template spacings

de/px-emails.json, de/px-platform.json, en-GB/px-emails.json, en/px-emails.json, en/px-platform.json, es/px-emails.json, es/px-platform.json
=> Release 20.3.8.0

en/px-common.json, es/px-common.json
Add recaptcha study entrance copies (ES, EN). DE missing.
=> Add recaptcha study entrance copies (ES, EN)

de/px-common.json
Add recaptcha study entrance copies (DE)
=> Add recaptcha study entrance copies (DE)

de/px-common.json, en/px-common.json, es/px-common.json
Intermediate branch for study entrance checks (captcha and paypal)
=> Intermediate branch for study entrance checks

de/px-common.json, en/px-common.json, es/px-common.json
=> Release 20.3.12.0

de/px-common.json, de/px-emails.json, en-GB/px-common.json, en-GB/px-emails.json, en/px-common.json, en/px-emails.json, es/px-common.json, es/px-emails.json
The reference to the name in the translations was incorrect. Some new translations for panel portal UI where also included by ux
[UZ-43054](https://uzjira.atlassian.net/browse/UZ-43054)
=> UZ-43054 - Changed variable for referencing name in emails

de/px-common.json, de/px-emails.json, en-GB/px-common.json, en-GB/px-emails.json, en/px-common.json, en/px-emails.json, es/px-common.json, es/px-emails.json
Missing translations in panel portal
=> UZ-51753 - Missing translations in panel portal

de/px-common.json, en-GB/px-common.json, en/px-common.json, es/px-common.json
This adds a few last remaining PO tags for MAR cards.
https://uzjira.atlassian.net/browse/UZ-51753
=> UZ-51753: last missing tags

de/px-common.json, en-GB/px-common.json, en-GB/px-demographics.json, en/px-common.json, es/px-common.json
This adds the new PO tags for the moderated sesson modal.
=> UZ-51811: adding expected PO tags for moderated session modal

da/px-common.json, da/px-platform.json, de/px-common.json, de/px-platform.json, en-GB/px-common.json, en-GB/px-platform.json, en/px-common.json, en/px-platform.json, es/px-common.json, es/px-platform.json, fr/px-common.json, fr/px-platform.json, nl/px-common.json, nl/px-platform.json, sv/px-common.json, sv/px-platform.json
This adds the new dialect PO tags and also two missing MAR-card-related PO tags.
=> UZ-50541: add new dialect PO tags

da/px-demographics.json, de/px-demographics.json, en-GB/px-demographics.json, en/px-demographics.json, es/px-demographics.json, fr/px-demographics.json, nl/px-demographics.json, sv/px-demographics.json
This makes employees profile question have the expected text, with company instead of organization.
It also adds some missing translations for Switzerland.
https://uzjira.atlassian.net/browse/UZ-55462
https://uzjira.atlassian.net/browse/UZ-55283
=> fix: make company appear instead of organization UZ-55462

da/px-demographics.json, de/px-demographics.json, en-GB/px-demographics.json, en/px-demographics.json, fr/px-demographics.json, nl/px-demographics.json, sv/px-demographics.json
Some labels on educations questions were not capitalised. Also misses some apostrph
[UZ-55548](https://uzjira.atlassian.net/browse/UZ-55548)
=> UZ-55548 - fix some education transaltions

da/px-demographics.json, fr/px-demographics.json, nl/px-demographics.json, sv/px-demographics.json
This adds the translations for education levels from various countries in different countries
https://uzjira.atlassian.net/browse/UZ-55804
=> fix: adding the translations for education levels from various countries in different countries UZ-55804

de/px-demographics.json
This updates px-demographics.json so that the education levels in various countries are available in German
https://uzjira.atlassian.net/browse/UZ-55804
=> fix: make sure that the education levels in various countries are available in German UZ-55804

fr/px-platform.json, sv/px-platform.json
This adds expanded demographics.
=> fix: adding expanded demographics

da/px-emails.json, es/px-emails.json, sv/px-emails.json
Fixes "Failed to send study complete" errors in communication-service (language `sv`)
=> fix: Failed to send study complete errors in communication-service (language sv)

da/px-common.json, de/px-common.json, en-GB/px-common.json, en/px-common.json, en/px-panel-management.json, es/px-common.json, fr/px-common.json, nl/px-common.json, sv/px-common.json
This makes Ethnicity US and GB be differentiated and corrects the someOf filter label
https://uzjira.atlassian.net/browse/UZ-59316
=> fix: make Ethnicity US and GB be differentiated and correct someOf filter label UZ-59316

en/px-panel-management.json
https://uzjira.atlassian.net/browse/UZ-59411
=> fix: add accepted/rejected (yes/no) translations to filter operator selectors UZ-59411

sv/px-emails.json
Update gotQuestions copy to be able to send swedish study complete email.
https://uzjira.atlassian.net/browse/UZ-59602
=> Update px-emails.json (POEditor.com)

da/px-emails.json, es/px-emails.json, fr/px-emails.json, sv/px-emails.json
Fixes
https://uzjira.atlassian.net/browse/UZ-59862
https://uzjira.atlassian.net/browse/UZ-59863
=> Fix missing projectId in scheduling cancellation emails UZ-59862 UZ-59863

en/px-panel-management.json
Fixes to technical issues and missing formatting
=> Panel Management UI - bulk actions TQA fixes

en/px-panel-management.json
Changes:
1. corrected label for selected panelists
2. added label for ID filter name
=> fix: corrected label for selected panelists UZ-60441

en/px-panel-management.json
This changes the status TOL PO Editor term to what should be used now.
https://uzjira.atlassian.net/browse/UZ-62222
=> fix: change status TOL PO Editor term UZ-62222

en/px-panel-management.json
https://uzjira.atlassian.net/browse/UZ-62928
=> fix: correct communications (accepted) filter PO tag UZ-62928

en/px-panel-management.json
https://uzjira.atlassian.net/browse/UZ-63457
=> fix: correct confirmation modal PO tags UZ-63457

da/px-countries.json, da/px-platform.json, de/px-countries.json, de/px-platform.json, en-GB/px-countries.json, en-GB/px-platform.json, en/px-countries.json, en/px-panel-management.json, en/px-platform.json, es/px-countries.json, es/px-platform.json, fr/px-countries.json, fr/px-platform.json, nl/px-countries.json, nl/px-platform.json, sv/px-countries.json, sv/px-platform.json
This adds the anonymized PO tag.
https://uzjira.atlassian.net/browse/UZ-63912
=> fix: make anonymized fields appear as such UZ-63912

da/px-common.json, de/px-common.json, en-GB/px-common.json, en/px-common.json, en/px-panel-management.json, es/px-common.json, fr/px-common.json, nl/px-common.json, sv/px-common.json
No translation is needed in languages other that English for the "Field can't be empty" PO tag.
https://uzjira.atlassian.net/browse/UZ-64047
=> Update px-panel-management.json UZ-64047

en/px-panel-management.json
This adds the changes applied tags for Panel Management UI/IPA.
=> fix: add changes applied tags

fr/px-common.json, fr/px-emails.json, fr/px-platform.json
Update translations from POEditor.
[RAD-15292]
[RAD-15292]: https://user-testing.atlassian.net/browse/RAD-15292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RAD-15292] Update translations

de/px-emails.json, de/px-platform.json, en-GB/px-emails.json, en-GB/px-platform.json, en/px-emails.json, en/px-platform.json, fr/px-emails.json, fr/px-platform.json
Update translations from POEditor.
https://user-testing.atlassian.net/browse/RAD-14282
=> [RAD-14282] Update translations

de/px-emails.json, de/px-platform.json, en-GB/px-emails.json, en-GB/px-platform.json, en/px-emails.json, en/px-platform.json, fr/px-emails.json, fr/px-platform.json
Reverts IntelliZoomPlatform/px-translations#173
=> Revert "[RAD-14282] Update translations"

de-AT/px-emails.json, de-CH/px-emails.json, de/px-emails.json, de/px-platform.json, en-GB/px-platform.json, en/px-emails.json, en/px-platform.json, es-MX/px-emails.json, fr/px-emails.json, fr/px-platform.json
Update payout from 21 to 14 days
https://user-testing.atlassian.net/browse/RAD-16970
#178
=> [RAD-16970] Poeditor tracking master

en/px-platform.json
New title for the verified Paypal account banner.
[RAD-24756](https://user-testing.atlassian.net/browse/RAD-24756)
https://github.com/IntelliZoomPlatform/panel-portal-ui/pull/574
[RAD-24756]: https://user-testing.atlassian.net/browse/RAD-24756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: new verified title RAD-24756

en/px-platform.json
Fixed new line formatting - https://user-testing.atlassian.net/browse/RAD-24754
https://user-testing.atlassian.net/browse/RAD-24754
https://github.com/IntelliZoomPlatform/panel-portal-ui/pull/573
=> fix: PayPal study entrance copy new line spacing RAD-24754

da/px-platform.json, de/px-platform.json, en-GB/px-platform.json, en/px-platform.json, es/px-platform.json, fr/px-platform.json, nl/px-platform.json, sv/px-platform.json
Pull down translations from Phrase
There's an unrelated change in `fr/px-platform.json` but it looks legitimate (fixes a typo) so I have decided to leave it in
https://user-testing.atlassian.net/browse/RAD-25221
=> feat: translations for PayPal changes RAD-25221

de/px-platform.json, es/px-platform.json, fr/px-platform.json
Some URL formatting fixes for translate tdokens
https://user-testing.atlassian.net/browse/RAD-25221
=> fix: PayPal integration tokens RAD-25221

config/ut-translator.yaml
Improve ut-translator config based on FX comments
https://user-testing.atlassian.net/browse/RAD-28641
=> fix: improve ut-translator config based on FX comments RAD-28641

da/px-emails.json, de-AT/px-emails.json, de-CH/px-emails.json, de/px-emails.json, en-GB/px-emails.json, en/px-emails.json, es-MX/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Pull tokens from Phrase
https://user-testing.atlassian.net/browse/RAD-28641
=> feat: pull tokens from Phrase RAD-28641

en/px-panel-management.json
Add new paypal token for panel management UI 
https://user-testing.atlassian.net/browse/RAD-37156
=> feat: add new paypal token for panel management UI RAD-37156

da/px-platform.json, de-AT/px-platform.json, de-CH/px-platform.json, de/px-platform.json, en-GB/px-platform.json, en/px-platform.json, es-MX/px-platform.json, es/px-platform.json, fr/px-platform.json, nl/px-platform.json, sv/px-platform.json
Adding new tokens for the changed IZ landing page copy.
https://user-testing.atlassian.net/browse/RAD-39533
=> feat: add new tokens for landing page RAD-39533

en/px-emails.json
- Add copies for email study complete 
[RAD-38867](https://user-testing.atlassian.net/browse/RAD-38867)
Specify other PRs involved in this ticket/feature.
[RAD-38867]: https://user-testing.atlassian.net/browse/RAD-38867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add copies RAD-38867

da/px-emails.json, de/px-emails.json, en/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Update variables to use the right name
https://user-testing.atlassian.net/browse/RAD-38867
=> fix: update variables to use the right name RAD-38867

da/px-emails.json, de/px-emails.json, en/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Update translations to use the right variables
https://user-testing.atlassian.net/browse/RAD-38867
=> fix: update translations to use the right variables RAD-38867

en/px-emails.json
Pull copies
https://user-testing.atlassian.net/browse/RAD-38867
=> fix: pull copies RAD-38867

da/px-emails.json, de-AT/px-emails.json, de-CH/px-emails.json, de/px-emails.json, en-GB/px-emails.json, en/px-emails.json, es-MX/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Pull copies from Phrase and update some live conversation generic copies.
https://user-testing.atlassian.net/browse/RAD-38870
=> fix: pull copies RAD-38870

da/px-emails.json, de-AT/px-emails.json, de-CH/px-emails.json, de/px-emails.json, en-GB/px-emails.json, en/px-emails.json, es-MX/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Pull tokens for panelist problem reported email
https://user-testing.atlassian.net/browse/RAD-40867
=> feat: pull tokens for panelist problem reported email RAD-40867

de/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Some translations for the unified have been updated, pulling the changes in.
[RAD-38866] not really related to that, just picked a random email templates ticket.
Specify other PRs involved in this ticket/feature.
[RAD-38866]: https://user-testing.atlassian.net/browse/RAD-38866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: updates to translations

da/px-emails.json, de-AT/px-emails.json, de-CH/px-emails.json, de/px-emails.json, en-GB/px-emails.json, en/px-emails.json, es-MX/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Fixed so that the URL is present in all languages. Added Mexican Spanish translations.
https://user-testing.atlassian.net/browse/RAD-41114
=> [RAD-41114] Fix links and Mexican translations

da/px-emails.json, de/px-emails.json, en/px-emails.json, es-MX/px-emails.json, es/px-emails.json, fr/px-emails.json, nl/px-emails.json, sv/px-emails.json
Pull email tokens
https://user-testing.atlassian.net/browse/RAD-38870
=> feat: pull email tokens RAD-38870
